name = "logfire-logs-proxy"
main = "src/index.ts"
compatibility_date = "2024-12-24"
compatibility_flags = ["nodejs_compat"]

[observability.logs]
enabled = true

[vars]
GITHUB_SHA = "unknown"

[env.staging]
name = "logfire-logs-proxy-staging"
vars = { GITHUB_SHA = "staging" }
